from . import product_template
from . import event_event
from . import res_partner
from . import student
from . import sale_order
from . import website
from . import learning_domain
from . import subject
from . import teacher
from . import account_invoice
from . import batch
from . import classroom
