# -*- coding: utf-8 -*-

{
    "name": 'Training Base',
    "version": "11.0.1.0.2",
    "depends": [
        '__export__',
        'base',
        'event',
        'event_sale',
        'partner_firstname',
        'product',
        'website_event_sale',
    ],
    "author": "Nicolas JEUDY, Odoo Community Association (OCA)",
    "installable": True,
    "data": [
        'security/training_security.xml',
        'views/product_template.xml',
        'views/batch.xml',
        'views/event_event.xml',
        'wizard/register_event.xml',
        'wizard/teacher_create_employee_wizard_view.xml',
        'wizard/event_registration_create_student.xml',
        'views/template.xml',
        'views/student.xml',
        'views/subject.xml',
        'views/teacher_view.xml',
        'ir_actions_act_window_records.xml',
        'ir_ui_menu_records.xml',
        'ir_module_category_records.xml',
        'ir_model_access_records.xml',
        'res_groups_records.xml',
    ],
}
